package com.therxmv.churros.core.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * Temporary placeholder entity required by Room KSP to generate AppDatabase_Impl.
 * Remove this once the first real feature entity is added to [AppDatabase].
 */
@Entity(tableName = "_build_placeholder")
internal data class BuildPlaceholderEntity(
    @PrimaryKey val id: Int = 0,
)

/**
 * Room database constructor used for non-JVM (iOS) targets.
 * The `actual` implementation is generated by Room KSP for each platform.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>

/**
 * The application Room database.
 *
 * Add feature entities to the [entities] array as features are implemented.
 * Remove [BuildPlaceholderEntity] when the first real entity is added.
 *
 * Migration strategy:
 *   - Pre-1.0: destructive fallback (see [getDatabaseBuilder])
 *   - 1.0+: versioned [androidx.room.migration.Migration] objects
 */
@Database(
    entities = [BuildPlaceholderEntity::class],
    version = 1,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase()
